[tool.black]
line-length = 120
target-version = ["py310"]
extend-exclude = '''
(
  ^FTMO_BOT_V2/
| ^vendor/
| ^logs/
| ^\.venv/
| ^.*\.ipynb$
| (^|.*/)(runner_(prev|bak|backup|fix).*\.py)$
| (^|.*/)(gpt_bridge_.*(bad|bak).*\.(py))$
)
'''
