name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - run: pip install black flake8
      - run: black --check .
      - run: flake8 .
   - name: Black (check only)
  run: |
    python -m pip install -U black
    black --check --extend-exclude '(^|/)(runner_(prev|bak|backup|fix).*\.py|gpt_bridge_.*(bad|bak).*\.py|.*\.ipynb$)' .
